[package]
distribution = "2201.10.0"
org = "ballerinax"
name = "hubspot.crm.properties"
version = "@toml.version@"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["hubspot", "CRM", "Properties Management", "Marketing Automation", "Customer Data", "Cost/Freemium"]
repository = "https://github.com/ballerina-platform/module-ballerinax-hubspot.crm.properties"

[build-options]
observabilityIncluded = true

[platform.java17]
graalvmCompatible = true
